### ISSUE TITLE
Can I run CoroBase without huge pages?

### ISSUE THREAD

**Issue by Cypredar** [sfu-dis/corobase#5]
Can I run CoroBase in an environment that without supporting huge pages?
I'm going to simulate CoroBase in Gem5's SE mode, which doesn't seem to support HugePages, and I'm wondering if there is an easy way to run CoroBase without the help of HugePages.
I also want to know if not using HugePages will cause any problems, is it reasonable for me to do so?

**Comment by wangtzh** [comment]
Yes, but that'd mean it's not going to use the in-house allocator (MM::allocate) which will not give high performance. So it should be only used for testing purposes; you can use the `tls-alloc` parameter to turn it on and off.
